### PR TITLE
Fix HTML escaping problems

### LINKED ISSUE #50: ActionView ap displays as string instead of HTML
I encountered this issue with awesome_print: https://github.com/awesome-print/awesome_print/issues/199

And discovered your fork, which I've just tried but it appears to have the same issue.

html-print

Am I doing something wrong or is this an ongoing issue?

- Rails 5.2.1
- amazing_print 1.2.1

### PR DESCRIPTION
**Pull request by daniel-rikowski**
This fixes #50 resp. awesome-print/awesome_print#199

Also this prevents the ActiveRecord formatters from emitting unescaped `#<ClassName#object_id>` or `Class < Superclass` strings, which couldn't be catched by the caller even with manual escaping. 

Existing code using workarounds like `<%= raw ap ... %>` or `<%= (ap ...).html_safe %>` will continue to work.

### CODE REVIEW

**Comment by paddor** [comment]
Thanks for the PR. I haven't touched Rails in forever. Can this be verified in a test case?

**Comment by HarlemSquirrel** [comment]
@daniel-rikowski Do you have some time to resolve the conflicts? Thank you!

**Comment by daniel-rikowski** [comment]
I rebased my pull request, but now tests are failing. It looks like https://github.com/amazing-print/amazing_print/commit/25352d2f0d91cf4c509fe0b89dc27da3bbe1f800 added an explicit test to enforce that the returned HTML is *not* marked as safe. It looks like it declares #50 to be the intended behaviour.

I'm not sure what to do here...

**Comment by HarlemSquirrel** [comment]
I wrote a test to verify how it works today. Could you update the test to verify this change?
Thank you!

**Comment by daniel-rikowski** [comment]
Oh, sorry, I didn't notice #65 🙈 

I updated the test and added a new one for the ActiveRecord subclass bug, i.e. the `<` in `ChildModel < ParentModel` wasn't escaped as `&lt;` when using `html: true`.

**Review by HarlemSquirrel — APPROVED** [review]
Thank you!

**Pull request merged**
