### PR TITLE
Add support for Ruby 3.3

### PR DESCRIPTION
**Pull request by HarlemSquirrel**

### CODE REVIEW

**Review by paddor — COMMENTED** [review]
Just on my phone right now but looks good to me. Why the change from `unix: true` to just `:unix`? Does it work?

**Comment by HarlemSquirrel** [comment]
> Just on my phone right now but looks good to me. Why the change from `unix: true` to just `:unix`? Does it work?

Yeah it was Robocop autocorrect

**Review by paddor — APPROVED** [review]

**Comment by paddor** [comment]
How to actually make it merge? I don't recognize GitHub anymore.

**Review by paddor — APPROVED** [review]

**Comment by HarlemSquirrel** [comment]
Lol thanks for that. Not sure what the hell happened.

**Pull request merged**
