### PR TITLE
Fix FrozenError

### PR DESCRIPTION
**Pull request by miyucy**
`align` will return frozen string.

### CODE REVIEW

**Review by agrberg — APPROVED** [review]
Looks good to me 👍 . As strings are being concat'ed into new instances this will create more items in memory but will prevent the frozen error.

**Comment by miyucy** [comment]
@agrberg Thanks for review! I thinks [this issue](https://github.com/amazing-print/amazing_print/issues/52) is related.

**Comment by paddor** [comment]
If you're okay with it, can we change it to an interpolated String? It's faster than using `String#+` multiple times.

**Comment by miyucy** [comment]
@paddor Sure. I'll change it. btw, should we also change [this line](https://github.com/amazing-print/amazing_print/pull/51/files#diff-b5f387afe8e968dc6a2110814ffd9b6fR93) ?

```ruby
      def pre_ruby19_syntax(key, value, width)
        align(key, width) + colorize(' => ', :hash) + inspector.awesome(value)
      end
```

**Review by paddor — CHANGES_REQUESTED** [review]
Please, something like:
```
"#{align(key, width - 1)}#{colorize(': ', :hash)}#{inspector.awesome(value)}"
```
Using `String#+` in this case creates unnecessary intermediate objects.

**Comment by paddor** [comment]
@miyucy Sorry, didn't see your new comment. But yes, change the other line as well 👍 thanks

**Review by paddor — APPROVED** [review]

**Comment by paddor** [comment]
Thanks!

**Pull request merged**
