### PR TITLE
 Don't monkey patch String class

### PR DESCRIPTION
**Pull request by n-rodriguez**
As explained here https://github.com/awesome-print/awesome_print/issues/419, monkey patch on `String` class was pretty unexpected.

The key is in `def colorize(str, type)` method : instead of monkey patching `String` + calling `'foo'.red`, let's define colors methods on `AmazingPrint::Colors` module and call `AmazingPrint::Colors.red('foo')` instead.

https://github.com/amazing-print/amazing_print/blob/8c0ae339e309b27badf45ec92bd5fb1176ed5c31/lib/amazing_print/colorize.rb#L9-L22

This way we don't pollute `String` class with new methods and we avoid clashes with `colorize` gem which I don't use due to license issues (gpl2 is contaminating) and we do not have to add a new dependency like Rainbow gem.

Thank you!

### CODE REVIEW

**Comment by ddarbyson** [comment]
nice to see some movement on this

**Review by paddor — DISMISSED** [review]
Yeah this is long overdue. Thank you. At first glance, this looks good to me.

**Review by HarlemSquirrel — COMMENTED** [review]
Thanks for working on this! This is very much needed.

Could you please check out the lints and make Robocop happy? 😁

**Comment by n-rodriguez** [comment]
> Could you please check out the lints and make Robocop happy? 😁

Done :)

**Review by HarlemSquirrel — APPROVED** [review]

**Comment by HarlemSquirrel** [comment]
Those other checks appear to be failing on master so we can fix those separately.

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
